/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_witness_securesmartcam_jpegredaction_JpegRedaction */

#ifndef _Included_org_witness_securesmartcam_jpegredaction_JpegRedaction
#define _Included_org_witness_securesmartcam_jpegredaction_JpegRedaction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_witness_securesmartcam_jpegredaction_JpegRedaction
 * Method:    redactit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_witness_securesmartcam_jpegredaction_JpegRedaction_redactRegion
  (JNIEnv *, jobject, jstring, jstring, int, int, int, int, jstring);

/*
*JNIEXPORT void JNICALL Java_org_witness_securesmartcam_jpegredaction_JpegRedaction_loadImage
*  (JNIEnv *, jobject);
*
*JNIEXPORT void JNICALL Java_org_witness_securesmartcam_jpegredaction_JpegRedaction_saveImage
*  (JNIEnv *, jobject);
*/

JNIEXPORT void JNICALL Java_org_witness_securesmartcam_jpegredaction_JpegRedaction_redactRegions
  (JNIEnv *, jobject, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
